Docs : Adding my Introduction
Bash-Woman-Community/Welcome pull request #18
Opened 2021-01-02 03:44 UTC by priyansh19

2021-01-02 05:36 UTC, jai-dewani requested changes
Hey @priyansh19, Thanks for the PR. 
Can you make sure each heading is starting in a new line. Refer #11 for the same

2021-01-02 06:44 UTC, ahammadshawki8 requested changes
Please solve the problems in your forked branch.

2021-01-02 06:44 UTC, ahammadshawki8 commented on Members.md
> +- __Name__: Priyansh Gupta
Add 2 spaces or more after your name

2021-01-02 06:44 UTC, ahammadshawki8 commented on Members.md
> +- __Name__: Priyansh Gupta
Add 2 or more spaces after your name
```suggestion
- __Name__: Priyansh Gupta   
```

2021-01-02 06:44 UTC, ahammadshawki8 commented on Members.md
> +__Tech Stack__: Java, Spring, BigData(Kafka, Hive, MapReduce, Spark) and DevOps.
Add 2 or more spaces after ending your tech stack.
```suggestion
__Tech Stack__: Java, Spring, BigData(Kafka, Hive, MapReduce, Spark), and DevOps.   
```

2021-01-02 07:52 UTC, priyansh19 commented on Members.md
> +- __Name__: Priyansh Gupta
Done !!

2021-01-02 07:52 UTC, priyansh19 commented on Members.md
> +__Tech Stack__: Java, Spring, BigData(Kafka, Hive, MapReduce, Spark) and DevOps.
Done !!

2021-01-02 07:53 UTC, priyansh19 commented
Team, Thanks for the review !!
@seema1711 please check and merge this PR 👍🏻

2021-01-02 08:36 UTC, jai-dewani approved these changes
Looks good @Bash-Woman-Community/maintainers

2021-01-02 09:39 UTC, seema1711 commented
There are some conflicts, @priyansh19. Please resolve them.

2021-01-04 02:41 UTC, ahammadshawki8 commented
There have been some updates to the members.md so make sure you update your forked repo and then update this PR to avoided merge conflicts

2021-01-04 02:57 UTC, ahammadshawki8 requested changes
There have been some updates to the members.md so make sure you update your forked repo and then update this PR to avoided merge conflicts

2021-01-06 18:43 UTC, merged