Update Members.md
Bash-Woman-Community/Welcome pull request #23
Opened 2021-01-02 10:23 UTC by amaan-ahmad

added my info

2021-01-02 14:01 UTC, jai-dewani requested changes
Hey @amaan-ahmad, Thanks for the PR. 
Please refer #11 to make sure you have all the information in separate lines

2021-01-04 02:44 UTC, ahammadshawki8 requested changes

2021-01-04 02:44 UTC, ahammadshawki8 commented on Members.md
> +
Add some spaces
```suggestion
- __Name__:  Amaan Ahmad  
__Country__:  India  
__About__:  Full-Stack web developer, I develop scalable web applications.  
__Tech Stack__:  ReactJS, NodeJS, Express, MongoDB, C++, Java, JavaScript  
__Social Handles__:  [Twitter](https://twitter.com/amaancodes) | [Email](mailto:amaan_ahmad_@outlook.com)  
__Website__:  [Blog](https://blog.amaan.codes)  

```

2021-01-05 08:30 UTC, amaan-ahmad commented
patched.

2021-01-05 08:31 UTC, amaan-ahmad commented
@jai-dewani kindly review and merge

2021-01-06 19:05 UTC, merged