Update Members.md
Bash-Woman-Community/Welcome pull request #50
Opened 2021-01-11 00:14 UTC by ritiksoni00

2021-01-11 00:14 UTC, ritiksoni00 commented
@seema1711 sorry i'm late!

2021-01-11 01:04 UTC, ahammadshawki8 requested changes
Great, Please solve the problems before merging it to the main branch.

2021-01-11 01:04 UTC, ahammadshawki8 commented on Members.md
> +
```suggestion
- __Name__: Ritik Soni   
__Country__: India  
__About__: to be 21 in upcoming Feb, Junior Year of bachelors. Danjgo maybe... learning stuff about CPP and Python frameworks.   
__Social Handles__: [Twitter](https://twitter.com/Arre_ritik) | [GitHub](https://github.com/ritiksoni00) | [LinkedIn](https://www.linkedin.com/in/ritik-soni/)   
```

2021-01-11 02:56 UTC, ritiksoni00 commented on Members.md
> +
done!

2021-01-11 09:41 UTC, ahammadshawki8 commented
Now it is ready for merging ✌

2021-01-12 13:32 UTC, merged

2021-01-12 13:33 UTC, plazzy99 requested changes

2021-01-12 13:33 UTC, plazzy99 commented on Members.md
> +__Country__: India
Please add *tech stack* and *website* if any