update members.md added my info
Bash-Woman-Community/Welcome pull request #51
Opened 2021-01-11 18:21 UTC by bagladivyang03

2021-01-11 18:22 UTC, bagladivyang03 commented
@ahammadshawki8 could u pls review and merge it :)

2021-01-12 02:23 UTC, ahammadshawki8 requested changes
Please solve this problems

2021-01-12 02:23 UTC, ahammadshawki8 commented on Members.md
> +__Website__:  [Portfolio](https://divyangbagla.vercel.app/)
Good job 👏

```suggestion

- __Name__: Divyang Bagla 
__Country__: India  
__About__: I am a Junior year CS undergraduate from MIT-WPU, Pune.I know web development technologies like Django, Bootstrap. I like to do competitive programming. I love learning new things. 
__Tech Stack__: C/C++, Python,MySQL,Django, BootStrap 
__Social Handles__: [LinkedIn](https://www.linkedin.com/in/divyang-bagla-976233176/) | [GitHub](https://github.com/bagladivyang03)  
__Website__: [Portfolio](https://divyangbagla.vercel.app/)  
```

2021-01-12 02:47 UTC, bagladivyang03 commented on Members.md
> +__Website__:  [Portfolio](https://divyangbagla.vercel.app/)
Thanks @ahammadshawki8 :)

2021-01-12 13:39 UTC, plazzy99 approved these changes

2021-01-12 13:39 UTC, merged