Update Members.md
Bash-Woman-Community/Welcome pull request #6
Opened 2020-12-29 13:44 UTC by AbhishekDoshi26

Added My Introduction

2020-12-30 17:40 UTC, seema1711 commented
Please refer to this PR https://github.com/Bash-Woman-Community/Welcome/pull/7

2021-01-01 10:49 UTC, jai-dewani requested changes
Hey @AbhishekDoshi26,   
There have been some updates to the `Members.md` so make sure you update your forked repo and then update this PR to avoided merge conflicts

2021-01-06 19:11 UTC, plazzy99 requested changes

2021-01-06 19:11 UTC, plazzy99 commented on Members.md
> +- About:  I am the one who loves to create beautiful apps with Flutter and help people, develop great apps and spread knowledge.! I am also the Semi-Finalist for Build For Digital India, 2020 organiz
follow the updated pattern of the member.md file

2021-02-02 21:22 UTC, plazzy99 commented
open this pr once resolved

2021-02-02 21:22 UTC, closed without merging